<a href="https://colab.research.google.com/github/wenko99/Standalone_DDL/blob/master/Lecture/Lec0_Colab_%26_Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hello Colaboratory!

Colaboratory는 구글에서 개발한 클라우드 기반 Jupyter Notebook 환경입니다.

여러분의 컴퓨터가 아닌 클라우드 서버 상에서 코드가 실행되며, GPU 1개를 무료로 제공해줍니다.(Tesla K80, 12시간/일)

GPU를 사용하려면 런타임을 설정해 주어야 합니다.

런타임 - 런타임 유형 변경에서 아래와 같이 Python 3, GPU로 설정해 주세요.

<p><img alt="Colaboratory logo" src="https://steemitimages.com/DQmbcq6Razbj69b1Ab6m5B6gkXK7FE7Gt8gSZmQifKaTwiS/colab3.png" align="left" hspace="10px" vspace="0px"></p>


그리고 다음과 같은 코드를 실행해봅니다. shift + Enter 혹은 Ctrl + Enter로 실행할 수 있습니다.

처음 실행시 클라우드 서버에 연결하는 과정을 거쳐야 하므로 조금 기다려 주어야 합니다.

In [0]:
print("hello world")

hello world




---


주피터 노트북의 특징은 블럭 단위로 실행할 수 있으며, 실행한 결과가 메모리 상으로 공유된다는 점입니다.

또한 마지막 줄에 있는 변수의 값을 자동으로 출력해 줍니다.

In [0]:
a = 123
b = 456
a += b
a

579



---


Colaboratory의 경우, Python의 유명한 패키지들이 이미 깔려 있습니다. <font color = "deepskyblue">Numpy, Pandas, Matplotlib, Scipy, Tensorflow, Pytorch</font> 등이 있고, 깔리지 않은 패키지의 경우 다음과 같은 코드를 실행하여 깔 수 있습니다.


```
!pip install tensorflow
```

!는 이 코드가 Python 코드가 아닌 터미널에서 실행하는 것임을 뜻합니다. 



---

\
## Numpy tutorial

아래는 Numpy를 이용한 간단한 코드입니다. Numpy는 행렬 계산 및 유용한 수식을 포함하는 패키지입니다.


In [0]:
import numpy as np

A = np.array([1.0, 2.0, 3.0])
print(A)
print(type(A))
print('\n')
print(np.zeros((2,3)))
print('\n')
print(np.random.random((2,3)))

[1. 2. 3.]
<class 'numpy.ndarray'>


[[0. 0. 0.]
 [0. 0. 0.]]


[[0.81002815 0.52058387 0.49891467]
 [0.70947284 0.74131258 0.28980242]]


<font color = "chartreuse">*shape*</font>는 이 행렬(혹은 배열)의 차원을 나타냅니다.

In [0]:
M = np.array([[1, 2], [3, 4]])
M.shape

(2, 2)

elemental wise한 행렬간의 사칙연산은 일반적인 사칙연산처럼 쓸 수 있습니다.

In [0]:
X = np.array([1.0, 2.0, 3.0])
Y = np.array([2.0, 4.0, 6.0])

print("X + Y =>", X + Y)
print("X - Y =>", X - Y)
print("X * Y =>", X * Y)
print("X / Y =>", X / Y)
print("X * 2 =>", X * 2)

X + Y => [3. 6. 9.]
X - Y => [-1. -2. -3.]
X * Y => [ 2.  8. 18.]
X / Y => [0.5 0.5 0.5]
X * 2 => [2. 4. 6.]


행렬곱은 다음과 같은 두가지 방식이 있습니다.

In [0]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [2, 1]])

print(A.dot(B))
print(np.dot(A, B))

[[ 5  4]
 [11 10]]
[[ 5  4]
 [11 10]]


행렬(혹은 배열)에 포함된 요소들의 합, 최소최댓값 뿐만 아니라 축에 따른 합/최소최댓값 역시 구할 수 있습니다.

In [0]:
A = np.random.random((2, 3))

print(A)

print("\nSum =>", A.sum())
print("Min =>", A.min())
print("Max =>", A.max(),"\n")

# axis: 축 방향
print(A.sum(axis=0)) # 각 열의 합
print(A.min(axis=1)) # 각 행의 최소값

[[0.27683226 0.38890007 0.617178  ]
 [0.3262117  0.20426973 0.65394244]]

Sum => 2.467334202971226
Min => 0.20426972647088382
Max => 0.6539424427215635 

[0.60304396 0.5931698  1.27112044]
[0.27683226 0.20426973]


아래 소개된 함수들은 행렬의 모양을 바꾸어주는 함수들입니다.

주의할 점은 A를 바꾸는 함수들과 A는 그대로 두고 바뀐 모양을 리턴하는 함수가 있다는 점입니다.

- **원래 행렬을 바꾸는 함수** : <font color = "chartreuse">*resize, shape에 값을 넣는 것*</font>

- **바뀐 행렬을 리턴하는 함수**: <font color = "chartreuse">*reshape, flatten, T*</font>

행렬의 모양을 바꾸는 함수에 -1을 인자로 주면, 알아서 사이즈에 맞춰 반환해줍니다.

아래와 같이 A.<font color = "chartreuse">reshape</font>(<font color = "mediumslateblue">3</font>, <font color = "mediumslateblue">-1</font>)을 실행하면 12를 3으로 나눈 4가 -1의 위치에 들어가게 되어, (3, 4) 행렬이 리턴됩니다.

In [0]:
A = np.arange(12)
print("A = ", A)

print('\n')
B = A.reshape(4, 3)
print("A = ", A)
print("B = ", B)

print('\n')
A.resize((3, 4)) 
print("A(resize)\n", A)

print('\n')
A.flatten()
print("Flatten\n", A.flatten())

print('\n')
A.T
print("Transpose\n", A.T)

print('\n')
A.shape = 2, 6
print("A(shape)\n", A)

print('\n')
A.reshape(3, -1)
print("Reshape\n", A.reshape(3, -1))

A =  [ 0  1  2  3  4  5  6  7  8  9 10 11]


A =  [ 0  1  2  3  4  5  6  7  8  9 10 11]
B =  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


A(resize)
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Flatten
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


Transpose
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


A(shape)
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


Reshape
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


<font color = "chartreuse">vstack</font>은 행렬을 1차원적으로 쌓는 함수입니다.

<font color = "chartreuse">hstack</font>은 행렬을 2차원적으로 쌓는 함수입니다.

<font color = "chartreuse">column_stack</font>은 1차원 배열에 대해서만 연산 가능합니다.

In [0]:
A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

print("vstack")
print(np.vstack((A, B)))

print('\nhstack')
print(np.hstack((A, B)))

A = np.array((1, 2, 3))
B = np.array((2, 3, 4))
print('\ncolumn stack')
print(np.column_stack((A, B)))


vstack
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack
[[1 2 5 6]
 [3 4 7 8]]

column stack
[[1 2]
 [2 3]
 [3 4]]


# Reference

* [코드로 보는 NumPy Tutorial](http://riseshia.github.io/2017/01/30/numpy-tutorial-with-code.html)
* ぜロから作るDeep Learning