<a href="https://colab.research.google.com/github/wenko99/Standalone_DDL/blob/master/Lec02/Lec02_NoTrain_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris_data = iris.data
iris_labels = iris.target

import pandas as pd

df = pd.DataFrame(iris_data)
df2 = pd.DataFrame(iris_labels)
df = pd.concat([df, df2], axis=1, sort=False)
df.columns = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Classes']

np.random.seed(7)
df = df.reindex(np.random.permutation(df.index))

iris_data = df.iloc[:, :4].values
iris_labels = df.iloc[:, 4].values

# Data Preprocessing

Set train_x and train_y for training data

Set test_x and test_y for testing data

In [0]:
n_train_data = 135

train_x = iris_data[ : n_train_data]
train_y = iris_labels[ : n_train_data]
test_x = iris_data[n_train_data : ]
test_y = iris_labels[n_train_data : ]

# Score Function

$ f(X) = WX + B$

$W.shape = (3,4)$

$X.shape = (4, )$

$B.shape = (3, )$

$f(X).shape = (3, )$

In [0]:
def score_function(X, W, B):
    return W.dot(X) + B

#SVM Loss 

##$L_{i} = \underset{j\neq y_i}\sum max(0 \ ,\ s_j - s_{y_i} + \triangle )$

##$L = {1\over N}\underset{i=1}{\overset{N}\sum} L_{i}$

In [0]:
def svm_loss(scores, y_i):
    loss = np.maximum(0 , scores - scores[y_i] + 1)
    loss[y_i] = 0
    return np.sum(loss)

#Softmax Function and Cross-entropy Loss

##$p_{i} = { e^{s_{y_i} - max(s) }\over\underset{j}\sum{ e^ {s_{j} - max(s)}  } }$

##$L_{i} = -\ log( p_{i}) $

##$L = {1\over N}\underset{i=1}{\overset{N}\sum} L_{i}$

In [0]:
import numpy as np

In [0]:
softmax([1,2,1])[0]

0.21194155761708544

In [0]:
def softmax(array):
    exps = np.exp(array - np.max(array))
    return exps / np.sum(exps)

In [0]:
def cross_entropy_loss(scores, y_i):
    return - np.log10(softmax(scores)[y_i])

#L2 Regularization

###$R(W) = \underset{k}\sum\underset{l}\sum {W_{kl}}^2$

In [0]:
W = np.ones((3,4))
l2_reg(W)

12.0

In [0]:
def l2_reg(W):
    return np.sum(np.square(W))

# Let's Test!

In [0]:
np.random.seed(123)
weight = np.random.uniform(-2, 2, (3,4))
bias = np.random.uniform(-5, 5, (3,))

print(weight)
print(bias)

[[ 0.78587674 -0.85544266 -1.09259419  0.20525908]
 [ 0.87787588 -0.30757416  1.92305679  0.73931895]
 [-0.07627239 -0.43152993 -0.62728794  0.91619883]]
[-0.61427755 -4.40322103 -1.01955745]


In [0]:
loss = 0
r = 0.05
for i in range(n_train_data):
    scores = score_function(train_x[i], weight, bias)
    loss += cross_entropy_loss(scores, train_y[i])

loss /= n_train_data
loss += r * l2_reg(weight)

print("Train loss is {:.3f}".format(loss))

Train loss is 3.348
