<a href="https://colab.research.google.com/github/wenko99/Standalone_DDL/blob/master/Lec02/Lec02_NoTrain_sk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris_data = iris.data
iris_labels = iris.target

import pandas as pd

df = pd.DataFrame(iris_data)
df2 = pd.DataFrame(iris_labels)
df = pd.concat([df, df2], axis=1, sort=False)
df.columns = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Classes']

np.random.seed(7)
df = df.reindex(np.random.permutation(df.index))

iris_data = df.iloc[:, :4].values
iris_labels = df.iloc[:, 4].values

# Data Preprocessing

Set train_x and train_y for training data

Set test_x and test_y for testing data

In [0]:
n_train_data = 135

train_x = iris_data[ : n_train_data]
train_y = iris_labels[ : n_train_data]
test_x = iris_data[n_train_data : ]
test_y = iris_labels[n_train_data : ]

# Score Function

$ f(X) = WX + B$

$W.shape = (3,4)$

$X.shape = (4, )$

$B.shape = (3, )$

$f(X).shape = (3, )$

In [0]:
def score_function(X, W, B):
    """
    
    W는 (3,4) 차원 행렬이고, X는 (4,), B는 (3,)의 차원을 갖습니다.
    
    우리가 원하는 score function을 구하기 위해서는 W와 X를 내적한 뒤, B와 element wise하게 덧셈을 해야 할 것입니다.
    
    따라서 이러한 형태가 되어야 할 것입니다.
    
    return W 내적 X + B
    
    Hint : Lec00 Colab&Numpy tutorial에 행렬곱(W*X가 아닙니다)과 element wise한 행렬간의 덧셈이 무엇인지 나와있습니다.
    
    """

#SVM Loss 

##$L_{i} = \underset{j\neq y_i}\sum max(0 \ ,\ s_j - s_{y_i} + \triangle )$

##$L = {1\over N}\underset{i=1}{\overset{N}\sum} L_{i}$

In [0]:
def svm_loss(scores, y_i):
    """
    
    이 svm_loss function은 위의 L_i를 구하는 함수입니다.
    
    scores는 score function을 통해 구해진 (3,)차원의 벡터(배열)입니다.
    
    즉, scores[0]는 setosa에 대한 score를 의미하는 것입니다.
    
    y_i는 L_i를 구할 때 나오는 y_i와 같습니다.
    
    즉, 정답을 가리킵니다.
    
    따라서 scores[y_i]는 정답 클래스에 대한 score를 의미할 것입니다.
    
    L_i 를 구할 때, margin은 1로 계산하시길 바랍니다.
    
    """

#Softmax Function and Cross-entropy Loss

##$p_{i} = { e^{s_{y_i} - max(s) }\over\underset{j}\sum{ e^ {s_{j} - max(s)}  } }$

##$L_{i} = -\ log( p_{i}) $

##$L = {1\over N}\underset{i=1}{\overset{N}\sum} L_{i}$

In [0]:
def softmax(scores, y_i):
    """
    
    scores는 svm_loss와 마찬가지로 점수를 나타내는 (3,)차원 벡터(배열)입니다.
    
    또한 y_i도 svm_loss와 마찬가지로 정답 라벨을 의미합니다.
    
    따라서 우리가 구하고자 하는 p_i 는 scores[y_i] - max(scores)를 exponential한 값을
    
    모든 score의 값에 max(scores)를 뺀 값을 exp로 계산하여 더한 값으로 나누면 나올 것입니다.
    
    이렇게 구해진 p_i를 return 하면 됩니다.
    
    exponential 함수는 np.exp()를 사용할 수 있습니다.
    
    (사실, np.exp함수는 element-wise하기 때문에, softmax를 적용한 배열을 리턴하도록 만들수도 있습니다. 차후 올라갈 코드는 이러한 방식을 사용할 것입니다.)
    
    """

In [0]:
def cross_entropy_loss(scores, y_i):
    """
    
    cross_entropy_loss 함수는 간단히 구할 수 있습니다.
    
    softmax(scores, y_i)에 log를 취한 값의 부호를 바꿔주면 L_i를 구할 수 있습니다.
    
    이것을 리턴하면 됩니다.
    
    """

#L2 Regularization

###$R(W) = \underset{k}\sum\underset{l}\sum {W_{kl}}^2$

In [0]:
def l2_reg(W):
    """
    
    W는 (3,4)차원의 행렬이므로 위의 식에서 k는 3, l은 4가 될 것입니다.
    
    즉, 다음과 같은 형태가 될 것입니다.
    
    for k in range(3):
        for l in range(4):
            W[k][l] ...
    
    L2 regularization 함수는 이러한 W의 각 element 값을 제곱하여 더해준 것이 될 것입니다.
    
    만일 위 과정을 쉽게 할 수 있으시다면, numpy를 이용하여 for문 없이 regularization term을 계산해 보세요!
    
    """

# Compute Loss

In [0]:
np.random.seed(123)
weight = np.random.uniform(-2, 2, (3,4))
bias = np.random.uniform(-5, 5, (3,))

print(weight)
print(bias)

[[ 0.78587674 -0.85544266 -1.09259419  0.20525908]
 [ 0.87787588 -0.30757416  1.92305679  0.73931895]
 [-0.07627239 -0.43152993 -0.62728794  0.91619883]]
[-0.61427755 -4.40322103 -1.01955745]


In [0]:
loss = 0
r = 0.05

for i in range(n_train_data):
    scores = score_function(train_x[i], weight, bias)
    #loss += svm_loss(scores, train_y[i])
    loss += cross_entropy_loss(scores, train_y[i])

loss /= n_train_data
loss += r * l2_reg(weight)

print("Train loss is {:.3f}".format(loss))

Train loss is 3.348
